apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-svc-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: employee-svc-service
                port:
                  number: 80
