FROM postgres:15

# Set environment variables for DB
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=company_db

# Copy initialization scripts (SQL or shell) into the container
COPY postgres/init.sql /docker-entrypoint-initdb.d/
